name: TestProject

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Upload repository
        uses: actions/checkout@v2

      - name: Sepup
        run: make setup

      - name: Check lint
        run: make lint

      - name: Run tests with coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test
          coverageLocations: ${{github.workplace}}/clover.xml:clover
          debug: true
